services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Refresj\RfrsjFontAwesome\:
        resource: "../Classes/*"

    Refresj\RfrsjFontAwesome\Middleware\AddFontAwesomeCss:
        public: true
        tags:
            - name: middlewares
